POST http://localhost:8080/api/public/categories
Content-Type: application/json

{
  "categoryName": "Kitchen"
}

### GET request with parameter

POST http://localhost:8080/api/public/categories
Content-Type: application/json

{
  "categoryName": "a"
}
