POST http://localhost:8080/api/admin/categories/2/products
Content-Type: application/json

{
  "productName": "Product4",
  "description": "Product description",
  "quantity": 10,
  "price": 500,
  "discount": 25
}
