POST http://localhost:8080/api/admin/categories/1/products
Content-Type: application/json

{
  "productName": "Product3",
  "description": "Product description",
  "quantity": 10,
  "price": 500,
  "discount": 15
}
